### ISSUE TITLE
I cannot find the hanpin package

### ISSUE THREAD

**Issue by wooego** [janvorisek/chinese-latex-utilities#1]
In the hanzibox.sty file, I see
`\RequirePackage{hanpin}`
But I cannot find it on CTAN  nor in google.
Would you please tell me where can I find it? thanks.

**Comment by janvorisek** [comment]
Package is now included in latex folder!

**Comment by liangching3** [comment]
hanpin.sty文件找不到，無法使用宏包。

**Comment by janvorisek** [comment]
> 
> 
> hanpin.sty文件找不到，無法使用宏包。

The file is part of the repository now.  https://github.com/janvorisek/chinese-latex-utilities/tree/master/latex

**Comment by liangching3** [comment]
Hello, I am honored to use your template, I can already use the Xelatex mode to compile the grid.tex template, I would like to ask how to make the effect of boxes with star (illustration of the figure)? Looking forward to your reply.
[cid:image003.png@01D50C2D.77AC9B80]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用


________________________________
发件人: Jan Vorisek <notifications@github.com>
发送时间: Thursday, May 16, 2019 5:59:55 PM
收件人: janvorisek/chinese-latex-utilities
抄送: liangching3; Comment
主题: Re: [janvorisek/chinese-latex-utilities] I cannot find the hanpin package (#1)


hanpin.sty文件找不到，o法使用宏包。

The file is part of the repository now. https://github.com/janvorisek/chinese-latex-utilities/tree/master/latex

―
