### ISSUE TITLE
maybe xpinyin package is better than hanpin.sty

### ISSUE THREAD

**Issue by registor** [janvorisek/chinese-latex-utilities#2]
I think maybe xpinyin package is better than hanpin.sty, because it provided more macro for typesetting Chinese pinyin.

In order to use xpinyin package I modify your \RequirePackage{hanpin} in line 15 to \RequirePackage{xpinyin}, then change the  \pinyin{\mm@pin} to \expandafter\pinyin\expandafter{\mm@pin} in line 102 and line 108.

The attach file is new hanzibox.sty I modified.

[hanzibox.zip](https://github.com/janvorisek/chinese-latex-utilities/files/3549680/hanzibox.zip)

**Comment by janvorisek** [comment]
I agree. To be honest I haven't investigated much about the available pinyin packages at the time of writing this utility. I've been working on an update recently based on xpinyin just as you note in your example.

Thanks for your feedback anyway and sorry for my late reply.
